---
services:
  backup:
    volumes:
      - var_log:/backup/logs:ro

volumes:
  var_log:
  var_sessions:
  backup_dumps:

networks:
  internal:
  proxy:
    external: true

secrets:
  symfony_env:
    file: .env.production
    name: symfony_env_${ENV_HASH:-latest}
